### ISSUE TITLE
v2 TODO LIST

### ISSUE THREAD

**Issue by Franckyi** [Franckyi/IBE-Editor#17]
## Functional

- [ ] Item Editor
- [ ] Block Editor
- [ ] Entity Editor
- [ ] NBT Editor **(NEW!)** 
- [ ] Bookmarks *(previously called IBE Clipboard)*
- [ ] Key Bindings
- [ ] Configuration
- [ ] `/ibe` Command

## Technical

- [ ] Setup development environment & build
- [ ] Create Data Binding API
- [ ] Create Game Hooks for Forge & Fabric compatibility
  - Client
    - [ ] Renderer hook
    - [ ] Key Bindings hook
    - [ ] Screen / Screen Scaling hook
    - [ ] ...
  - Common
    - [ ] Item / Item Factory hook
    - [ ] Block / WorldBlock / Block Factory hook
    - [ ] Entity / WorldEntity/ Entity Factory hook
    - [ ] Player hook
    - [ ] World hook
    - [ ] Tag Factory hook
    - [ ] Text Factory hook
    - [ ] Pos hook
    - [ ] Slot hook
    - [ ] Network / Buffer / Packet hook
    - [ ] Command hook
    - [ ] ...
- [ ] Rewrite GUAPI (GUI API) to use Game Hooks & Data Binding API
  - [ ] Implement Vanilla Theme
- [ ] Create Forge & Fabric mods
- [ ] Packet handling
