### ISSUE TITLE
TODO list for future versions of IBE Editor

### ISSUE THREAD

**Issue by Franckyi** [Franckyi/IBE-Editor#8]
## 1.14+ enhancements

This is a list of the enhancements that will be done for a future version.

### General
- [ ] GUAPI rewrite
  - It will allow me to develop a Fabric version of the mod, compatible with snapshots
- [ ] Code documentation

### Block Editor
- [ ] Tile entities
    - [ ] Capabilities
        - [ ] Fluid handler
        - [ ] Energy
    - [ ] A category for each tile entity
        - [ ] Banner editor (patterns, colors)
        - [ ] etc...

### Entity Editor
- [ ] A category for each entity
    - [ ] Horse editor (speed, jump height...)
    - [ ] etc...

### Miscellaneous
- [ ] I18n (Internationalization, translation)
- [x] Editor wiki and guides (hosted on GitHub)
